# 배열 (Array)

- 리스트 타입이 배열 기능을 제공하고 있음


In [1]:
import queue
data_queue = queue.Queue()

In [2]:
data_queue.put('funcoding')
data_queue.put(1)

In [3]:
data_queue.qsize()

2

In [6]:
data_queue.get()

'funcoding'

In [7]:
data_queue.qsize()

1

In [8]:
data_queue.get()

1

In [9]:
data_queue.qsize()

0

#### LifeQueue()로 큐 만들기 (LIFO)

In [11]:
lifeQueue = queue.LifoQueue()

lifeQueue.put('funcoding')
lifeQueue.put(1)

In [12]:
lifeQueue.qsize()

2

In [13]:
lifeQueue.get()

1

### PriorityQueue()

In [14]:
data_queue = queue.PriorityQueue()

In [15]:
data_queue.put((10, 'korea')) # 튜플을 입력으로 함
data_queue.put((5, 1))
data_queue.put((15, 'china'))

In [16]:
data_queue.qsize()

3

In [17]:
data_queue.get()

(5, 1)

### 큐가 많이 쓰이는 곳
* 멀티 테스킹을 위한 프로세스 스케쥴링 방식 구현

### 리스트 변수로 enqueue, dequeue 기능 구현해보기

In [19]:
queue_list = list()

def enqueue(data):
    queue_list.append(data)

def dequeue():
    data = queue_list[0]
    del queue_list[0]
    return data

In [20]:
for index in range(10):
    enqueue(index)

In [21]:
len(queue_list)

10

In [25]:
dequeue()

3

In [26]:
len(queue_list)

6

In [27]:
import numpy as np

In [32]:
temp = np.array([[[0, 0, 1], [1, 2, 0], [3, 2, 1]],
                 [[3, 1, 0], [2, 0, 3], [0, 0, 1]],
                 [[1, 0, 0], [2, 0, 0], [0, 1, 1]]
                ]
)
print(temp)

np.argmax(temp, axis=-1, keepdims=False)

[[[0 0 1]
  [1 2 0]
  [3 2 1]]

 [[3 1 0]
  [2 0 3]
  [0 0 1]]

 [[1 0 0]
  [2 0 0]
  [0 1 1]]]


array([[2, 1, 0],
       [0, 2, 2],
       [0, 0, 1]], dtype=int64)

In [38]:
temp1 = np.arange(6).reshape((2, 3)) + 20
print(temp1)
print(np.argmax(temp1))
print(np.argmax(temp1, axis=0))
print(np.argmax(temp1, axis=1))

[[20 21 22]
 [23 24 25]]
5
[1 1 1]
[2 2]
